# -*- coding: utf-8 -*-
"""task 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i2HkWFJfm-cvyV15uMPgFbCuYgJUpWab
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, accuracy_score

data = pd.read_csv('/content/drive/My Drive/IRIS.csv')

data.columns

data.head()

data.shape

data.info()

data.describe()

data.isnull().sum()

data['sepal_length'].hist()

data['sepal_width'].hist()

data['petal_length'].hist()

data['petal_width'].hist()

sns.pairplot(data, hue='species')
plt.show()

x = data.drop('species', axis=1)
x

y = data['species']
y

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

print(x.shape, x_train.shape, x_test.shape)

knn = KNeighborsClassifier(n_neighbors = 3)
knn.fit(x_train, y_train)

y_pred = knn.predict(x_test)

print ('Accuracy: ', accuracy_score(y_test, y_pred))

print (classification_report(y_test, y_pred))

x_test.head(2)

new_data = pd.DataFrame({'sepal_length':6.3,'sepal_width':3.3, 'petal_length':6.0, 'petal_width':2.5}, index=[0])

prediction = knn.predict(new_data)

prediction[0]

data.iloc[100:]

